# Generated by Django 5.2.1 on 2025-05-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='twilio_recording_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
