# Generated by Django 5.2.1 on 2025-05-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_twilio_recording_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='summary_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='call',
            name='summary_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='call',
            name='transcribe_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='call',
            name='transcribe_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
